//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecureData", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.Users")]
    public partial class SecureData : object
    {
        
        private string PassExtendField;
        
        private string PassHashField;
        
        private long UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassExtend
        {
            get
            {
                return this.PassExtendField;
            }
            set
            {
                this.PassExtendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassHash
        {
            get
            {
                return this.PassHashField;
            }
            set
            {
                this.PassHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.Users")]
    public partial class User : object
    {
        
        private string AddressField;
        
        private System.DateTime BirthDateField;
        
        private string CatalogField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private System.Nullable<bool> GenderField;
        
        private string GmtZoneField;
        
        private string LastNameField;
        
        private string MiddleNameField;
        
        private string MobilePhoneField;
        
        private string OtherPhone1Field;
        
        private string OtherPhone2Field;
        
        private short StatusField;
        
        private long UserIDField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Catalog
        {
            get
            {
                return this.CatalogField;
            }
            set
            {
                this.CatalogField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GmtZone
        {
            get
            {
                return this.GmtZoneField;
            }
            set
            {
                this.GmtZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone
        {
            get
            {
                return this.MobilePhoneField;
            }
            set
            {
                this.MobilePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherPhone1
        {
            get
            {
                return this.OtherPhone1Field;
            }
            set
            {
                this.OtherPhone1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherPhone2
        {
            get
            {
                return this.OtherPhone2Field;
            }
            set
            {
                this.OtherPhone2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProviderType", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class ProviderType : object
    {
        
        private string FileFormatField;
        
        private string ProviderNameField;
        
        private System.Uri ProviderUriField;
        
        private int TVProgProviderIDField;
        
        private TVProgService.EnumsTypeProg TypeEnumField;
        
        private string TypeNameField;
        
        private int TypeProgIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileFormat
        {
            get
            {
                return this.FileFormatField;
            }
            set
            {
                this.FileFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri ProviderUri
        {
            get
            {
                return this.ProviderUriField;
            }
            set
            {
                this.ProviderUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TVProgProviderID
        {
            get
            {
                return this.TVProgProviderIDField;
            }
            set
            {
                this.TVProgProviderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TVProgService.EnumsTypeProg TypeEnum
        {
            get
            {
                return this.TypeEnumField;
            }
            set
            {
                this.TypeEnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeProgID
        {
            get
            {
                return this.TypeProgIDField;
            }
            set
            {
                this.TypeProgIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.TypeProg", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.Common")]
    public enum EnumsTypeProg : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XMLTV = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InterTV = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemChannel", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class SystemChannel : object
    {
        
        private int ChannelIDField;
        
        private string DiffField;
        
        private string FileName25Field;
        
        private string FileNameOrigField;
        
        private System.Nullable<long> IconIDField;
        
        private string ImageWebSrcField;
        
        private System.Nullable<int> InternalIDField;
        
        private int OrderColField;
        
        private string SystemTitleField;
        
        private int TVProgViewerIDField;
        
        private string TitleField;
        
        private int UserChannelIDField;
        
        private string UserTitleField;
        
        private bool VisibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelID
        {
            get
            {
                return this.ChannelIDField;
            }
            set
            {
                this.ChannelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diff
        {
            get
            {
                return this.DiffField;
            }
            set
            {
                this.DiffField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName25
        {
            get
            {
                return this.FileName25Field;
            }
            set
            {
                this.FileName25Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNameOrig
        {
            get
            {
                return this.FileNameOrigField;
            }
            set
            {
                this.FileNameOrigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IconID
        {
            get
            {
                return this.IconIDField;
            }
            set
            {
                this.IconIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageWebSrc
        {
            get
            {
                return this.ImageWebSrcField;
            }
            set
            {
                this.ImageWebSrcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InternalID
        {
            get
            {
                return this.InternalIDField;
            }
            set
            {
                this.InternalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderCol
        {
            get
            {
                return this.OrderColField;
            }
            set
            {
                this.OrderColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemTitle
        {
            get
            {
                return this.SystemTitleField;
            }
            set
            {
                this.SystemTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TVProgViewerID
        {
            get
            {
                return this.TVProgViewerIDField;
            }
            set
            {
                this.TVProgViewerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserChannelID
        {
            get
            {
                return this.UserChannelIDField;
            }
            set
            {
                this.UserChannelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserTitle
        {
            get
            {
                return this.UserTitleField;
            }
            set
            {
                this.UserTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserChannel", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class UserChannel : object
    {
        
        private int ChannelIDField;
        
        private string FileName25Field;
        
        private string FileNameOrigField;
        
        private System.Nullable<long> IconIDField;
        
        private string ImageWebSrcField;
        
        private System.Nullable<int> InternalIDField;
        
        private int OrderColField;
        
        private int TVProgViewerIDField;
        
        private string TitleField;
        
        private int UserChannelIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelID
        {
            get
            {
                return this.ChannelIDField;
            }
            set
            {
                this.ChannelIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName25
        {
            get
            {
                return this.FileName25Field;
            }
            set
            {
                this.FileName25Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNameOrig
        {
            get
            {
                return this.FileNameOrigField;
            }
            set
            {
                this.FileNameOrigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> IconID
        {
            get
            {
                return this.IconIDField;
            }
            set
            {
                this.IconIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageWebSrc
        {
            get
            {
                return this.ImageWebSrcField;
            }
            set
            {
                this.ImageWebSrcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InternalID
        {
            get
            {
                return this.InternalIDField;
            }
            set
            {
                this.InternalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderCol
        {
            get
            {
                return this.OrderColField;
            }
            set
            {
                this.OrderColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TVProgViewerID
        {
            get
            {
                return this.TVProgViewerIDField;
            }
            set
            {
                this.TVProgViewerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserChannelID
        {
            get
            {
                return this.UserChannelIDField;
            }
            set
            {
                this.UserChannelIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemProgramme", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class SystemProgramme : object
    {
        
        private string AnonsContentField;
        
        private int CIDField;
        
        private string CategoryField;
        
        private string ChannelContentField;
        
        private string ChannelNameField;
        
        private int ChannelNumberField;
        
        private string DayMonthField;
        
        private string GenreContentField;
        
        private string GenreNameField;
        
        private string GenrePathField;
        
        private System.Nullable<int> InternalChanIDField;
        
        private System.Nullable<int> OrderColField;
        
        private long ProgrammeIDField;
        
        private long ProgrammesIDField;
        
        private string RatingContentField;
        
        private string RatingNameField;
        
        private int RemainField;
        
        private System.DateTimeOffset StartField;
        
        private System.DateTimeOffset StopField;
        
        private string TelecastCategoryField;
        
        private string TelecastDescrField;
        
        private string TelecastTitleField;
        
        private System.DateTimeOffset TsStartField;
        
        private System.DateTime TsStartMOField;
        
        private System.DateTime TsStopMOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnonsContent
        {
            get
            {
                return this.AnonsContentField;
            }
            set
            {
                this.AnonsContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CID
        {
            get
            {
                return this.CIDField;
            }
            set
            {
                this.CIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelContent
        {
            get
            {
                return this.ChannelContentField;
            }
            set
            {
                this.ChannelContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelName
        {
            get
            {
                return this.ChannelNameField;
            }
            set
            {
                this.ChannelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChannelNumber
        {
            get
            {
                return this.ChannelNumberField;
            }
            set
            {
                this.ChannelNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DayMonth
        {
            get
            {
                return this.DayMonthField;
            }
            set
            {
                this.DayMonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreContent
        {
            get
            {
                return this.GenreContentField;
            }
            set
            {
                this.GenreContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreName
        {
            get
            {
                return this.GenreNameField;
            }
            set
            {
                this.GenreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenrePath
        {
            get
            {
                return this.GenrePathField;
            }
            set
            {
                this.GenrePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InternalChanID
        {
            get
            {
                return this.InternalChanIDField;
            }
            set
            {
                this.InternalChanIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderCol
        {
            get
            {
                return this.OrderColField;
            }
            set
            {
                this.OrderColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProgrammeID
        {
            get
            {
                return this.ProgrammeIDField;
            }
            set
            {
                this.ProgrammeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProgrammesID
        {
            get
            {
                return this.ProgrammesIDField;
            }
            set
            {
                this.ProgrammesIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingContent
        {
            get
            {
                return this.RatingContentField;
            }
            set
            {
                this.RatingContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingName
        {
            get
            {
                return this.RatingNameField;
            }
            set
            {
                this.RatingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Remain
        {
            get
            {
                return this.RemainField;
            }
            set
            {
                this.RemainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Start
        {
            get
            {
                return this.StartField;
            }
            set
            {
                this.StartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Stop
        {
            get
            {
                return this.StopField;
            }
            set
            {
                this.StopField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelecastCategory
        {
            get
            {
                return this.TelecastCategoryField;
            }
            set
            {
                this.TelecastCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelecastDescr
        {
            get
            {
                return this.TelecastDescrField;
            }
            set
            {
                this.TelecastDescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelecastTitle
        {
            get
            {
                return this.TelecastTitleField;
            }
            set
            {
                this.TelecastTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset TsStart
        {
            get
            {
                return this.TsStartField;
            }
            set
            {
                this.TsStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TsStartMO
        {
            get
            {
                return this.TsStartMOField;
            }
            set
            {
                this.TsStartMOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TsStopMO
        {
            get
            {
                return this.TsStopMOField;
            }
            set
            {
                this.TsStopMOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgPeriod", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial struct ProgPeriod
    {
        
        private System.DateTimeOffset dtEndField;
        
        private System.DateTimeOffset dtStartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset dtEnd
        {
            get
            {
                return this.dtEndField;
            }
            set
            {
                this.dtEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset dtStart
        {
            get
            {
                return this.dtStartField;
            }
            set
            {
                this.dtStartField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genre", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class Genre : object
    {
        
        private System.DateTimeOffset CreateDateField;
        
        private System.DateTimeOffset DeleteDateField;
        
        private int GenreIDField;
        
        private string GenreNameField;
        
        private string GenrePathField;
        
        private int IconIDField;
        
        private long UIDField;
        
        private bool VisibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset DeleteDate
        {
            get
            {
                return this.DeleteDateField;
            }
            set
            {
                this.DeleteDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenreID
        {
            get
            {
                return this.GenreIDField;
            }
            set
            {
                this.GenreIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreName
        {
            get
            {
                return this.GenreNameField;
            }
            set
            {
                this.GenreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenrePath
        {
            get
            {
                return this.GenrePathField;
            }
            set
            {
                this.GenrePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IconID
        {
            get
            {
                return this.IconIDField;
            }
            set
            {
                this.IconIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenreClassif", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class GenreClassif : object
    {
        
        private string ContainPhrasesField;
        
        private System.Nullable<System.DateTime> DeleteAfterDateField;
        
        private long GIDField;
        
        private long GenreClassificatorIDField;
        
        private string GenreNameField;
        
        private string GenrePathField;
        
        private string NonContainPhrasesField;
        
        private System.Nullable<int> OrderColField;
        
        private System.Nullable<long> UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainPhrases
        {
            get
            {
                return this.ContainPhrasesField;
            }
            set
            {
                this.ContainPhrasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteAfterDate
        {
            get
            {
                return this.DeleteAfterDateField;
            }
            set
            {
                this.DeleteAfterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GID
        {
            get
            {
                return this.GIDField;
            }
            set
            {
                this.GIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GenreClassificatorID
        {
            get
            {
                return this.GenreClassificatorIDField;
            }
            set
            {
                this.GenreClassificatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenreName
        {
            get
            {
                return this.GenreNameField;
            }
            set
            {
                this.GenreNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenrePath
        {
            get
            {
                return this.GenrePathField;
            }
            set
            {
                this.GenrePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonContainPhrases
        {
            get
            {
                return this.NonContainPhrasesField;
            }
            set
            {
                this.NonContainPhrasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderCol
        {
            get
            {
                return this.OrderColField;
            }
            set
            {
                this.OrderColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class Rating : object
    {
        
        private System.DateTimeOffset CreateDateField;
        
        private System.DateTimeOffset DeleteDateField;
        
        private int IconIDField;
        
        private int RatingIDField;
        
        private string RatingNameField;
        
        private string RatingPathField;
        
        private long UIDField;
        
        private bool VisibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset DeleteDate
        {
            get
            {
                return this.DeleteDateField;
            }
            set
            {
                this.DeleteDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IconID
        {
            get
            {
                return this.IconIDField;
            }
            set
            {
                this.IconIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RatingID
        {
            get
            {
                return this.RatingIDField;
            }
            set
            {
                this.RatingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingName
        {
            get
            {
                return this.RatingNameField;
            }
            set
            {
                this.RatingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingPath
        {
            get
            {
                return this.RatingPathField;
            }
            set
            {
                this.RatingPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Visible
        {
            get
            {
                return this.VisibleField;
            }
            set
            {
                this.VisibleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RatingClassif", Namespace="http://schemas.datacontract.org/2004/07/TVProgViewer.BusinessLogic.ProgObjs")]
    public partial class RatingClassif : object
    {
        
        private string ContainPhrasesField;
        
        private System.Nullable<System.DateTime> DeleteAfterDateField;
        
        private string NonContainPhrasesField;
        
        private System.Nullable<int> OrderColField;
        
        private long RIDField;
        
        private long RatingClassificatorIDField;
        
        private string RatingNameField;
        
        private string RatingPathField;
        
        private long UIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainPhrases
        {
            get
            {
                return this.ContainPhrasesField;
            }
            set
            {
                this.ContainPhrasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeleteAfterDate
        {
            get
            {
                return this.DeleteAfterDateField;
            }
            set
            {
                this.DeleteAfterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NonContainPhrases
        {
            get
            {
                return this.NonContainPhrasesField;
            }
            set
            {
                this.NonContainPhrasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderCol
        {
            get
            {
                return this.OrderColField;
            }
            set
            {
                this.OrderColField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RID
        {
            get
            {
                return this.RIDField;
            }
            set
            {
                this.RIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RatingClassificatorID
        {
            get
            {
                return this.RatingClassificatorIDField;
            }
            set
            {
                this.RatingClassificatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingName
        {
            get
            {
                return this.RatingNameField;
            }
            set
            {
                this.RatingNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingPath
        {
            get
            {
                return this.RatingPathField;
            }
            set
            {
                this.RatingPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UID
        {
            get
            {
                return this.UIDField;
            }
            set
            {
                this.UIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TVProgService.IMainService")]
    public interface IMainService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddUser", ReplyAction="http://tempuri.org/IMainService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string userName, string passHash, string passExtend, string lastName, string firstName, string middleName, System.DateTime birthDate, System.Nullable<bool> gender, string email, string mobPhone, string otherPhone1, string otherPhone2, string address, string gmtZone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetHashes", ReplyAction="http://tempuri.org/IMainService/GetHashesResponse")]
        System.Threading.Tasks.Task<TVProgService.SecureData> GetHashesAsync(string username);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUser", ReplyAction="http://tempuri.org/IMainService/GetUserResponse")]
        System.Threading.Tasks.Task<TVProgService.GetUserResponse> GetUserAsync(TVProgService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetProviderTypeList", ReplyAction="http://tempuri.org/IMainService/GetProviderTypeListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.ProviderType>> GetProviderTypeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetSystemChannelList", ReplyAction="http://tempuri.org/IMainService/GetSystemChannelListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemChannel>> GetSystemChannelListAsync(int TVProgProviderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserChannelList", ReplyAction="http://tempuri.org/IMainService/GetUserChannelListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.UserChannel>> GetUserChannelListAsync(long uid, int typeProgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserInSystemChannels", ReplyAction="http://tempuri.org/IMainService/GetUserInSystemChannelsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemChannel>> GetUserInSystemChannelsAsync(long uid, int progProviderID, int typeProgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetSystemProgrammeList", ReplyAction="http://tempuri.org/IMainService/GetSystemProgrammeListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> GetSystemProgrammeListAsync(int typeProgID, System.DateTimeOffset dateTimeOffset, int mode, string category, string sidx, string sord, int page, int rows, string genres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetSystemProgrammePeriod", ReplyAction="http://tempuri.org/IMainService/GetSystemProgrammePeriodResponse")]
        System.Threading.Tasks.Task<TVProgService.ProgPeriod> GetSystemProgrammePeriodAsync(int typeProgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetSystemProgrammeDayList", ReplyAction="http://tempuri.org/IMainService/GetSystemProgrammeDayListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemProgramme>> GetSystemProgrammeDayListAsync(int typeProgID, int cid, System.DateTime tsStart, System.DateTime tsStop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/InsertUserChannel", ReplyAction="http://tempuri.org/IMainService/InsertUserChannelResponse")]
        System.Threading.Tasks.Task InsertUserChannelAsync(int userChannelID, long uid, int tvProgProviderID, int cid, string displayName, int orderCol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DeleteUserChannel", ReplyAction="http://tempuri.org/IMainService/DeleteUserChannelResponse")]
        System.Threading.Tasks.Task DeleteUserChannelAsync(long uid, int cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserProgrammeList", ReplyAction="http://tempuri.org/IMainService/GetUserProgrammeListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> GetUserProgrammeListAsync(long uid, int typeProgID, System.DateTimeOffset dateTimeOffset, int mode, string category, string sidx, string sord, int page, int rows, string genres);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetUserProgrammeDayList", ReplyAction="http://tempuri.org/IMainService/GetUserProgrammeDayListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemProgramme>> GetUserProgrammeDayListAsync(long uid, int typeProgID, int cid, System.DateTime tsStart, System.DateTime tsStop, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetCategories", ReplyAction="http://tempuri.org/IMainService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/SearchProgramme", ReplyAction="http://tempuri.org/IMainService/SearchProgrammeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> SearchProgrammeAsync(int typeProgID, string findTitle, string category, string sidx, string sord, int page, int rows, string genres, string dates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/SearchUserProgramme", ReplyAction="http://tempuri.org/IMainService/SearchUserProgrammeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> SearchUserProgrammeAsync(long uid, int typeProgID, string findTitle, string category, string sidx, string sord, int page, int rows, string genres, string dates);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpdateCatalog", ReplyAction="http://tempuri.org/IMainService/UpdateCatalogResponse")]
        System.Threading.Tasks.Task UpdateCatalogAsync(long uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ChangeChannelImage", ReplyAction="http://tempuri.org/IMainService/ChangeChannelImageResponse")]
        System.Threading.Tasks.Task ChangeChannelImageAsync(long uid, int userChannelId, string filename, string contentType, int length, int length25, string pathOrig, string path25);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetGenres", ReplyAction="http://tempuri.org/IMainService/GetGenresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.Genre>> GetGenresAsync(System.Nullable<long> uid, bool all);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddGenre", ReplyAction="http://tempuri.org/IMainService/AddGenreResponse")]
        System.Threading.Tasks.Task<long> AddGenreAsync(System.Nullable<long> uid, string name, System.Nullable<int> iconId, bool visible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpdateGenre", ReplyAction="http://tempuri.org/IMainService/UpdateGenreResponse")]
        System.Threading.Tasks.Task UpdateGenreAsync(long genreId, string name, bool visible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DeleteGenre", ReplyAction="http://tempuri.org/IMainService/DeleteGenreResponse")]
        System.Threading.Tasks.Task DeleteGenreAsync(long genreId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ChangeGenreImage", ReplyAction="http://tempuri.org/IMainService/ChangeGenreImageResponse")]
        System.Threading.Tasks.Task ChangeGenreImageAsync(long uid, long genreId, string filename, string contentType, int length, string pathOrig, string path25);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetGenreClassificators", ReplyAction="http://tempuri.org/IMainService/GetGenreClassificatorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.GenreClassif>> GetGenreClassificatorsAsync(System.Nullable<long> uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddGenreClassificator", ReplyAction="http://tempuri.org/IMainService/AddGenreClassificatorResponse")]
        System.Threading.Tasks.Task<long> AddGenreClassificatorAsync(long gid, System.Nullable<long> uid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpdateGenreClassificator", ReplyAction="http://tempuri.org/IMainService/UpdateGenreClassificatorResponse")]
        System.Threading.Tasks.Task UpdateGenreClassificatorAsync(long genreClassificatorId, long gid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DeleteGenreClassificator", ReplyAction="http://tempuri.org/IMainService/DeleteGenreClassificatorResponse")]
        System.Threading.Tasks.Task DeleteGenreClassificatorAsync(long genreClassificatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpGenreClassificateElem", ReplyAction="http://tempuri.org/IMainService/UpGenreClassificateElemResponse")]
        System.Threading.Tasks.Task UpGenreClassificateElemAsync(long genreClassificatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DownGenreClassificateElem", ReplyAction="http://tempuri.org/IMainService/DownGenreClassificateElemResponse")]
        System.Threading.Tasks.Task DownGenreClassificateElemAsync(long genreClassificatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetRatings", ReplyAction="http://tempuri.org/IMainService/GetRatingsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.Rating>> GetRatingsAsync(long uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddRating", ReplyAction="http://tempuri.org/IMainService/AddRatingResponse")]
        System.Threading.Tasks.Task<long> AddRatingAsync(long uid, string name, System.Nullable<int> iconId, bool visible);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpdateRating", ReplyAction="http://tempuri.org/IMainService/UpdateRatingResponse")]
        System.Threading.Tasks.Task UpdateRatingAsync(long ratingId, string name, bool visible, System.Nullable<System.DateTimeOffset> deleteDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DeleteRating", ReplyAction="http://tempuri.org/IMainService/DeleteRatingResponse")]
        System.Threading.Tasks.Task DeleteRatingAsync(long ratingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/ChangeRatingImage", ReplyAction="http://tempuri.org/IMainService/ChangeRatingImageResponse")]
        System.Threading.Tasks.Task ChangeRatingImageAsync(long uid, long ratingId, string filename, string contentType, int length, string pathOrig, string path25);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/GetRatingClassificators", ReplyAction="http://tempuri.org/IMainService/GetRatingClassificatorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.RatingClassif>> GetRatingClassificatorsAsync(long uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/AddRatingClassificator", ReplyAction="http://tempuri.org/IMainService/AddRatingClassificatorResponse")]
        System.Threading.Tasks.Task<long> AddRatingClassificatorAsync(long rid, long uid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpdateRatingClassificator", ReplyAction="http://tempuri.org/IMainService/UpdateRatingClassificatorResponse")]
        System.Threading.Tasks.Task UpdateRatingClassificatorAsync(long ratingClassificatorId, long rid, string containPhrases, string nonContainPrhases, System.Nullable<System.DateTime> deleteAfterDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DeleteRatingClassificator", ReplyAction="http://tempuri.org/IMainService/DeleteRatingClassificatorResponse")]
        System.Threading.Tasks.Task DeleteRatingClassificatorAsync(long ratingClassificatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/UpRatingClassificateElem", ReplyAction="http://tempuri.org/IMainService/UpRatingClassificateElemResponse")]
        System.Threading.Tasks.Task UpRatingClassificateElemAsync(long ratingClassificatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMainService/DownRatingClassificateElem", ReplyAction="http://tempuri.org/IMainService/DownRatingClassificateElemResponse")]
        System.Threading.Tasks.Task DownRatingClassificateElemAsync(long ratingClassificatorId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long uid;
        
        public GetUserRequest()
        {
        }
        
        public GetUserRequest(long uid)
        {
            this.uid = uid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TVProgService.User GetUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int errCode;
        
        public GetUserResponse()
        {
        }
        
        public GetUserResponse(TVProgService.User GetUserResult, int errCode)
        {
            this.GetUserResult = GetUserResult;
            this.errCode = errCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMainServiceChannel : TVProgService.IMainService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MainServiceClient : System.ServiceModel.ClientBase<TVProgService.IMainService>, TVProgService.IMainService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MainServiceClient() : 
                base(MainServiceClient.GetDefaultBinding(), MainServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMainService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), MainServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MainServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string userName, string passHash, string passExtend, string lastName, string firstName, string middleName, System.DateTime birthDate, System.Nullable<bool> gender, string email, string mobPhone, string otherPhone1, string otherPhone2, string address, string gmtZone)
        {
            return base.Channel.AddUserAsync(userName, passHash, passExtend, lastName, firstName, middleName, birthDate, gender, email, mobPhone, otherPhone1, otherPhone2, address, gmtZone);
        }
        
        public System.Threading.Tasks.Task<TVProgService.SecureData> GetHashesAsync(string username)
        {
            return base.Channel.GetHashesAsync(username);
        }
        
        public System.Threading.Tasks.Task<TVProgService.GetUserResponse> GetUserAsync(TVProgService.GetUserRequest request)
        {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.ProviderType>> GetProviderTypeListAsync()
        {
            return base.Channel.GetProviderTypeListAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemChannel>> GetSystemChannelListAsync(int TVProgProviderID)
        {
            return base.Channel.GetSystemChannelListAsync(TVProgProviderID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.UserChannel>> GetUserChannelListAsync(long uid, int typeProgID)
        {
            return base.Channel.GetUserChannelListAsync(uid, typeProgID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemChannel>> GetUserInSystemChannelsAsync(long uid, int progProviderID, int typeProgID)
        {
            return base.Channel.GetUserInSystemChannelsAsync(uid, progProviderID, typeProgID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> GetSystemProgrammeListAsync(int typeProgID, System.DateTimeOffset dateTimeOffset, int mode, string category, string sidx, string sord, int page, int rows, string genres)
        {
            return base.Channel.GetSystemProgrammeListAsync(typeProgID, dateTimeOffset, mode, category, sidx, sord, page, rows, genres);
        }
        
        public System.Threading.Tasks.Task<TVProgService.ProgPeriod> GetSystemProgrammePeriodAsync(int typeProgID)
        {
            return base.Channel.GetSystemProgrammePeriodAsync(typeProgID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemProgramme>> GetSystemProgrammeDayListAsync(int typeProgID, int cid, System.DateTime tsStart, System.DateTime tsStop)
        {
            return base.Channel.GetSystemProgrammeDayListAsync(typeProgID, cid, tsStart, tsStop);
        }
        
        public System.Threading.Tasks.Task InsertUserChannelAsync(int userChannelID, long uid, int tvProgProviderID, int cid, string displayName, int orderCol)
        {
            return base.Channel.InsertUserChannelAsync(userChannelID, uid, tvProgProviderID, cid, displayName, orderCol);
        }
        
        public System.Threading.Tasks.Task DeleteUserChannelAsync(long uid, int cid)
        {
            return base.Channel.DeleteUserChannelAsync(uid, cid);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> GetUserProgrammeListAsync(long uid, int typeProgID, System.DateTimeOffset dateTimeOffset, int mode, string category, string sidx, string sord, int page, int rows, string genres)
        {
            return base.Channel.GetUserProgrammeListAsync(uid, typeProgID, dateTimeOffset, mode, category, sidx, sord, page, rows, genres);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.SystemProgramme>> GetUserProgrammeDayListAsync(long uid, int typeProgID, int cid, System.DateTime tsStart, System.DateTime tsStop, string category)
        {
            return base.Channel.GetUserProgrammeDayListAsync(uid, typeProgID, cid, tsStart, tsStop, category);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> SearchProgrammeAsync(int typeProgID, string findTitle, string category, string sidx, string sord, int page, int rows, string genres, string dates)
        {
            return base.Channel.SearchProgrammeAsync(typeProgID, findTitle, category, sidx, sord, page, rows, genres, dates);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.List<TVProgService.SystemProgramme>>> SearchUserProgrammeAsync(long uid, int typeProgID, string findTitle, string category, string sidx, string sord, int page, int rows, string genres, string dates)
        {
            return base.Channel.SearchUserProgrammeAsync(uid, typeProgID, findTitle, category, sidx, sord, page, rows, genres, dates);
        }
        
        public System.Threading.Tasks.Task UpdateCatalogAsync(long uid)
        {
            return base.Channel.UpdateCatalogAsync(uid);
        }
        
        public System.Threading.Tasks.Task ChangeChannelImageAsync(long uid, int userChannelId, string filename, string contentType, int length, int length25, string pathOrig, string path25)
        {
            return base.Channel.ChangeChannelImageAsync(uid, userChannelId, filename, contentType, length, length25, pathOrig, path25);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.Genre>> GetGenresAsync(System.Nullable<long> uid, bool all)
        {
            return base.Channel.GetGenresAsync(uid, all);
        }
        
        public System.Threading.Tasks.Task<long> AddGenreAsync(System.Nullable<long> uid, string name, System.Nullable<int> iconId, bool visible)
        {
            return base.Channel.AddGenreAsync(uid, name, iconId, visible);
        }
        
        public System.Threading.Tasks.Task UpdateGenreAsync(long genreId, string name, bool visible)
        {
            return base.Channel.UpdateGenreAsync(genreId, name, visible);
        }
        
        public System.Threading.Tasks.Task DeleteGenreAsync(long genreId)
        {
            return base.Channel.DeleteGenreAsync(genreId);
        }
        
        public System.Threading.Tasks.Task ChangeGenreImageAsync(long uid, long genreId, string filename, string contentType, int length, string pathOrig, string path25)
        {
            return base.Channel.ChangeGenreImageAsync(uid, genreId, filename, contentType, length, pathOrig, path25);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.GenreClassif>> GetGenreClassificatorsAsync(System.Nullable<long> uid)
        {
            return base.Channel.GetGenreClassificatorsAsync(uid);
        }
        
        public System.Threading.Tasks.Task<long> AddGenreClassificatorAsync(long gid, System.Nullable<long> uid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate)
        {
            return base.Channel.AddGenreClassificatorAsync(gid, uid, containPhrases, nonContainPhrases, deleteAfterDate);
        }
        
        public System.Threading.Tasks.Task UpdateGenreClassificatorAsync(long genreClassificatorId, long gid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate)
        {
            return base.Channel.UpdateGenreClassificatorAsync(genreClassificatorId, gid, containPhrases, nonContainPhrases, deleteAfterDate);
        }
        
        public System.Threading.Tasks.Task DeleteGenreClassificatorAsync(long genreClassificatorId)
        {
            return base.Channel.DeleteGenreClassificatorAsync(genreClassificatorId);
        }
        
        public System.Threading.Tasks.Task UpGenreClassificateElemAsync(long genreClassificatorId)
        {
            return base.Channel.UpGenreClassificateElemAsync(genreClassificatorId);
        }
        
        public System.Threading.Tasks.Task DownGenreClassificateElemAsync(long genreClassificatorId)
        {
            return base.Channel.DownGenreClassificateElemAsync(genreClassificatorId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.Rating>> GetRatingsAsync(long uid)
        {
            return base.Channel.GetRatingsAsync(uid);
        }
        
        public System.Threading.Tasks.Task<long> AddRatingAsync(long uid, string name, System.Nullable<int> iconId, bool visible)
        {
            return base.Channel.AddRatingAsync(uid, name, iconId, visible);
        }
        
        public System.Threading.Tasks.Task UpdateRatingAsync(long ratingId, string name, bool visible, System.Nullable<System.DateTimeOffset> deleteDate)
        {
            return base.Channel.UpdateRatingAsync(ratingId, name, visible, deleteDate);
        }
        
        public System.Threading.Tasks.Task DeleteRatingAsync(long ratingId)
        {
            return base.Channel.DeleteRatingAsync(ratingId);
        }
        
        public System.Threading.Tasks.Task ChangeRatingImageAsync(long uid, long ratingId, string filename, string contentType, int length, string pathOrig, string path25)
        {
            return base.Channel.ChangeRatingImageAsync(uid, ratingId, filename, contentType, length, pathOrig, path25);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TVProgService.RatingClassif>> GetRatingClassificatorsAsync(long uid)
        {
            return base.Channel.GetRatingClassificatorsAsync(uid);
        }
        
        public System.Threading.Tasks.Task<long> AddRatingClassificatorAsync(long rid, long uid, string containPhrases, string nonContainPhrases, System.Nullable<System.DateTime> deleteAfterDate)
        {
            return base.Channel.AddRatingClassificatorAsync(rid, uid, containPhrases, nonContainPhrases, deleteAfterDate);
        }
        
        public System.Threading.Tasks.Task UpdateRatingClassificatorAsync(long ratingClassificatorId, long rid, string containPhrases, string nonContainPrhases, System.Nullable<System.DateTime> deleteAfterDate)
        {
            return base.Channel.UpdateRatingClassificatorAsync(ratingClassificatorId, rid, containPhrases, nonContainPrhases, deleteAfterDate);
        }
        
        public System.Threading.Tasks.Task DeleteRatingClassificatorAsync(long ratingClassificatorId)
        {
            return base.Channel.DeleteRatingClassificatorAsync(ratingClassificatorId);
        }
        
        public System.Threading.Tasks.Task UpRatingClassificateElemAsync(long ratingClassificatorId)
        {
            return base.Channel.UpRatingClassificateElemAsync(ratingClassificatorId);
        }
        
        public System.Threading.Tasks.Task DownRatingClassificateElemAsync(long ratingClassificatorId)
        {
            return base.Channel.DownRatingClassificateElemAsync(ratingClassificatorId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMainService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMainService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:3999/MainService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MainServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMainService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MainServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMainService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMainService,
        }
    }
}
