SET IDENTITY_INSERT dbo.MediaPic ON
GO
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (1, 'Untype.png', 'image/png', 'gzip', 3601, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (2, 'hudFilm.gif', 'image/gif', 'gzip', 676, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (3, 'teleserial.png', 'image/png', 'gzip', 4298, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (4, 'balloons.gif', 'image/gif', 'gzip', 1081, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (5, 'sport.png', 'image/png', 'gzip', 1771, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (6, 'docs.png', 'image/png', 'gzip', 4381, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (7, 'info.png', 'image/png', 'gzip', 1668, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (8, 'humor.png', 'image/png', 'gzip', 4463, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (9, 'teleshow.png', 'image/png', 'gzip', 4689, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (10, 'telegames.png', 'image/png', 'gzip', 4427, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (11, 'theater.png', 'image/png', 'gzip', 4607, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (12, 'multfilm.png', 'image/png', 'gzip', 1444, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (13, 'criminal.png', 'image/png', 'gzip', 3593, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (14, 'music.png', 'image/png', 'gzip', 3738, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (15, 'web.png', 'image/png', 'gzip', 1788, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (16, 'animals.png', 'image/png', 'gzip', 1508, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (17, 'weather.png', 'image/png', 'gzip', 1377, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (18, 'art.png', 'image/png', 'gzip', 1777, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (19, 'politic.png', 'image/png', 'gzip', 647, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (20, 'science.png', 'image/png', 'gzip', 1730, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (21, 'travel.png', 'image/png', 'gzip', 1871, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (22, 'people.png', 'image/png', 'gzip', 1573, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (23, 'tech.png', 'image/png', 'gzip', 4234, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (24, 'fashion.png', 'image/png', 'gzip', 4424, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (25, 'auto.png', 'image/png', 'gzip', 3979, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (26, 'medicine.png', 'image/png', 'gzip', 3921, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (27, 'religion.png', 'image/png', 'gzip', 4129, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (28, 'gardening.png', 'image/png', 'gzip', 1265, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (29, 'advertize.png', 'image/png', 'gzip', 4422, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (30, 'female.png', 'image/png', 'gzip', 560, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (31, 'cooking.png', 'image/png', 'gzip', 4452, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (32, 'extrime.png', 'image/png', 'gzip', 1478, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (33, 'finance.png', 'image/png', 'gzip', 3877, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (34, 'erotic.png', 'image/png', 'gzip', 1363, null, 1, '/imgs/system/genre/', '/imgs/system/genre/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (35, 'favempty.png', 'image/png', 'gzip', 2866, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (36, 'favblue.png', 'image/png', 'gzip', 4082, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (37, 'favpurple.png', 'image/png', 'gzip', 4027, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (38, 'favgreen.png', 'image/png', 'gzip', 4126, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (39, 'favyellow.png', 'image/png', 'gzip', 4024, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
INSERT INTO dbo.MediaPic ([IconID],[FileName],[ContentType],[ContentCoding],[Length],[Length25],[IsSystem],[PathOrig],[Path25])
VALUES (40, 'favpink.png', 'image/png', 'gzip', 3307, null, 1, '/imgs/system/fav/', '/imgs/system/fav/')
SET IDENTITY_INSERT dbo.MediaPic OFF

SELECT * FROM dbo.MediaPic