//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtUserSettings
    {
        public int ExtUserSettingsID { get; set; }
        public long UID { get; set; }
        public int TVProgProviderID { get; set; }
        public Nullable<short> UncheckedChannels { get; set; }
    
        public virtual TVProgProviders TVProgProviders { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
