//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreClassificator
    {
        public long GenreClassificatorID { get; set; }
        public long GID { get; set; }
        public Nullable<long> UID { get; set; }
        public string ContainPhrases { get; set; }
        public string NonContainPhrases { get; set; }
        public Nullable<int> OrderCol { get; set; }
        public Nullable<System.DateTime> DeleteAfterDate { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
