//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogActions
    {
        public int LogID { get; set; }
        public string Login { get; set; }
        public Nullable<System.DateTimeOffset> TsAction { get; set; }
        public short TypeAction { get; set; }
        public string MessageAction { get; set; }
        public string IP { get; set; }
        public string UserAgent { get; set; }
    }
}
