//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TVProgBaseEntities : DbContext
    {
        public TVProgBaseEntities()
            : base("name=TVProgBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channels> Channels { get; set; }
        public virtual DbSet<ExtUserSettings> ExtUserSettings { get; set; }
        public virtual DbSet<GenreClassificator> GenreClassificator { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<LogActions> LogActions { get; set; }
        public virtual DbSet<MediaPic> MediaPic { get; set; }
        public virtual DbSet<Programmes> Programmes { get; set; }
        public virtual DbSet<RatingClassificator> RatingClassificator { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<SearchSettings> SearchSettings { get; set; }
        public virtual DbSet<SystemUsers> SystemUsers { get; set; }
        public virtual DbSet<TVProgProviders> TVProgProviders { get; set; }
        public virtual DbSet<TypeProg> TypeProg { get; set; }
        public virtual DbSet<UpdateProgLog> UpdateProgLog { get; set; }
        public virtual DbSet<UserChannels> UserChannels { get; set; }
        public virtual DbSet<UsersPrograms> UsersPrograms { get; set; }
        public virtual DbSet<WebResources> WebResources { get; set; }
    
        [DbFunction("TVProgBaseEntities", "fnGetGenreContent")]
        public virtual IQueryable<string> fnGetGenreContent(Nullable<long> uID, string title)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[TVProgBaseEntities].[fnGetGenreContent](@UID, @Title)", uIDParameter, titleParameter);
        }
    
        [DbFunction("TVProgBaseEntities", "fnGetGenreName")]
        public virtual IQueryable<string> fnGetGenreName(Nullable<long> uID, string title)
        {
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("UID", uID) :
                new ObjectParameter("UID", typeof(long));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[TVProgBaseEntities].[fnGetGenreName](@UID, @Title)", uIDParameter, titleParameter);
        }
    }
}
