//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVProgBaseEntities : DbContext
    {
        public TVProgBaseEntities()
            : base("name=TVProgBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channels> Channels { get; set; }
        public virtual DbSet<ExtUserSettings> ExtUserSettings { get; set; }
        public virtual DbSet<GenreClassificator> GenreClassificator { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<LogActions> LogActions { get; set; }
        public virtual DbSet<MediaPic> MediaPic { get; set; }
        public virtual DbSet<Programmes> Programmes { get; set; }
        public virtual DbSet<RatingClassificator> RatingClassificator { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<SearchSettings> SearchSettings { get; set; }
        public virtual DbSet<SystemUsers> SystemUsers { get; set; }
        public virtual DbSet<TVProgProviders> TVProgProviders { get; set; }
        public virtual DbSet<TypeProg> TypeProg { get; set; }
        public virtual DbSet<UpdateProgLog> UpdateProgLog { get; set; }
        public virtual DbSet<UserChannels> UserChannels { get; set; }
        public virtual DbSet<UsersPrograms> UsersPrograms { get; set; }
        public virtual DbSet<WebResources> WebResources { get; set; }
    }
}
