//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programmes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programmes()
        {
            this.UsersPrograms = new HashSet<UsersPrograms>();
        }
    
        public long ProgrammesID { get; set; }
        public int TID { get; set; }
        public int CID { get; set; }
        public Nullable<int> InternalChanID { get; set; }
        public System.DateTimeOffset TsStart { get; set; }
        public System.DateTimeOffset TsStop { get; set; }
        public System.DateTime TsStartMO { get; set; }
        public System.DateTime TsStopMO { get; set; }
        public string Title { get; set; }
        public string Descr { get; set; }
        public string Category { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual TypeProg TypeProg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrograms> UsersPrograms { get; set; }
    }
}
