//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingClassificator
    {
        public long RatingClassificatorID { get; set; }
        public long RID { get; set; }
        public long UID { get; set; }
        public string ContainPhrases { get; set; }
        public string NonContainPhrases { get; set; }
        public Nullable<int> OrderCol { get; set; }
        public Nullable<System.DateTime> DeleteAfterDate { get; set; }
    
        public virtual Ratings Ratings { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
