//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ratings()
        {
            this.RatingClassificator = new HashSet<RatingClassificator>();
            this.UsersPrograms = new HashSet<UsersPrograms>();
        }
    
        public long RatingID { get; set; }
        public long UID { get; set; }
        public Nullable<long> IconID { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public string RatingName { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.DateTimeOffset> DeleteDate { get; set; }
    
        public virtual MediaPic MediaPic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingClassificator> RatingClassificator { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrograms> UsersPrograms { get; set; }
    }
}
