//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchSettings
    {
        public int SearchSettingsID { get; set; }
        public long UID { get; set; }
        public bool LoadSettings { get; set; }
        public string Match { get; set; }
        public string NotMatch { get; set; }
        public Nullable<bool> InAnons { get; set; }
        public Nullable<System.DateTime> TsFinalFrom { get; set; }
        public Nullable<System.DateTime> TsFinalTo { get; set; }
        public Nullable<int> TrackBarFrom { get; set; }
        public Nullable<int> TrackBarTo { get; set; }
    
        public virtual SystemUsers SystemUsers { get; set; }
    }
}
