//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUsers()
        {
            this.ExtUserSettings = new HashSet<ExtUserSettings>();
            this.GenreClassificator = new HashSet<GenreClassificator>();
            this.Genres = new HashSet<Genres>();
            this.RatingClassificator = new HashSet<RatingClassificator>();
            this.Ratings = new HashSet<Ratings>();
            this.SearchSettings = new HashSet<SearchSettings>();
            this.UserChannels = new HashSet<UserChannels>();
            this.UsersPrograms = new HashSet<UsersPrograms>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string PassHash { get; set; }
        public string PassExtend { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTimeOffset CreateDate { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Email { get; set; }
        public string MobPhoneNumber { get; set; }
        public string OtherPhoneNumber1 { get; set; }
        public string OtherPhoneNumber2 { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string GmtZone { get; set; }
        public short Status { get; set; }
        public string Catalog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtUserSettings> ExtUserSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenreClassificator> GenreClassificator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genres> Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingClassificator> RatingClassificator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ratings> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchSettings> SearchSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChannels> UserChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrograms> UsersPrograms { get; set; }
    }
}
