//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeProg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeProg()
        {
            this.Programmes = new HashSet<Programmes>();
            this.WebResources = new HashSet<WebResources>();
        }
    
        public int TypeProgID { get; set; }
        public int TVProgProviderID { get; set; }
        public string TypeName { get; set; }
        public string FileFormat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programmes> Programmes { get; set; }
        public virtual TVProgProviders TVProgProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebResources> WebResources { get; set; }
    }
}
