//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateProgLog
    {
        public long UpdateProgLogID { get; set; }
        public int WRID { get; set; }
        public System.DateTimeOffset TsUpdateStart { get; set; }
        public System.DateTimeOffset TsUpdateEnd { get; set; }
        public Nullable<int> UdtElapsedSec { get; set; }
        public System.DateTimeOffset MinProgDate { get; set; }
        public System.DateTimeOffset MaxProgDate { get; set; }
        public int QtyChans { get; set; }
        public int QtyProgrammes { get; set; }
        public int QtyNewChans { get; set; }
        public int QtyNewProgrammes { get; set; }
        public bool IsSuccess { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual WebResources WebResources { get; set; }
    }
}
