//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPrograms
    {
        public long UserProgramsID { get; set; }
        public long UID { get; set; }
        public int UCID { get; set; }
        public long PID { get; set; }
        public Nullable<long> GID { get; set; }
        public Nullable<long> RID { get; set; }
        public string Anons { get; set; }
        public bool Remind { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual Programmes Programmes { get; set; }
        public virtual Ratings Ratings { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
        public virtual UserChannels UserChannels { get; set; }
    }
}
