//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChannels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserChannels()
        {
            this.UsersPrograms = new HashSet<UsersPrograms>();
        }
    
        public int UserChannelID { get; set; }
        public long UID { get; set; }
        public int CID { get; set; }
        public Nullable<long> IconID { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> OrderCol { get; set; }
    
        public virtual Channels Channels { get; set; }
        public virtual MediaPic MediaPic { get; set; }
        public virtual SystemUsers SystemUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPrograms> UsersPrograms { get; set; }
    }
}
