//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebResources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebResources()
        {
            this.UpdateProgLog = new HashSet<UpdateProgLog>();
        }
    
        public int WebResourceID { get; set; }
        public int TPID { get; set; }
        public string FileName { get; set; }
        public string ResourceName { get; set; }
        public string ResourceUrl { get; set; }
    
        public virtual TypeProg TypeProg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UpdateProgLog> UpdateProgLog { get; set; }
    }
}
