//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVProgViewer.TVProgApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVProgViewer.TVProgApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить настройки временной зоны?.
        /// </summary>
        internal static string AcceptTimeDiffText {
            get {
                return ResourceManager.GetString("AcceptTimeDiffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подчёркивание.
        /// </summary>
        internal static string AccetuationText {
            get {
                return ResourceManager.GetString("AccetuationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alert {
            get {
                object obj = ResourceManager.GetObject("Alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap All {
            get {
                object obj = ResourceManager.GetObject("All", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и до ....
        /// </summary>
        internal static string AndToText {
            get {
                return ResourceManager.GetString("AndToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Антенна.
        /// </summary>
        internal static string AntennaText {
            get {
                return ResourceManager.GetString("AntennaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение уже запущено.
        /// </summary>
        internal static string AppAlreadyRunText {
            get {
                return ResourceManager.GetString("AppAlreadyRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможности аудиоустройства\n.
        /// </summary>
        internal static string AudioCapabilitiesText {
            get {
                return ResourceManager.GetString("AudioCapabilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число аудиоканалов не поддерживается.\n\n.
        /// </summary>
        internal static string AudioChannelsNotSupportText {
            get {
                return ResourceManager.GetString("AudioChannelsNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудиокодек не поддерживается..
        /// </summary>
        internal static string AudioCodecNotSupportText {
            get {
                return ResourceManager.GetString("AudioCodecNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудиоустройство не поддерживается..
        /// </summary>
        internal static string AudioDeviceNotSupportText {
            get {
                return ResourceManager.GetString("AudioDeviceNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный размер линии:\t\t{4}\n.
        /// </summary>
        internal static string AudioMaxSizeLinesText {
            get {
                return ResourceManager.GetString("AudioMaxSizeLinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный размер линии:\t\t{3}\n.
        /// </summary>
        internal static string AudioMinSizeLinesText {
            get {
                return ResourceManager.GetString("AudioMinSizeLinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио-частота не поддерживается.\n\n.
        /// </summary>
        internal static string AudioRateNotSupportText {
            get {
                return ResourceManager.GetString("AudioRateNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер аудио линии не поддерживается.\n\n.
        /// </summary>
        internal static string AudioSizeNotSupportText {
            get {
                return ResourceManager.GetString("AudioSizeNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя установить этот источник.\nПожалуйста, обратитесь к отчету об ошибке.\n.
        /// </summary>
        internal static string AudioSourceNotSupportText {
            get {
                return ResourceManager.GetString("AudioSourceNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио.
        /// </summary>
        internal static string AudioText {
            get {
                return ResourceManager.GetString("AudioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задне-диагональный.
        /// </summary>
        internal static string BackwardDiagonalText {
            get {
                return ResourceManager.GetString("BackwardDiagonalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bell {
            get {
                object obj = ResourceManager.GetObject("bell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bellempty {
            get {
                object obj = ResourceManager.GetObject("bellempty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bellFilt {
            get {
                object obj = ResourceManager.GetObject("bellFilt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bellheader {
            get {
                object obj = ResourceManager.GetObject("bellheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бит.
        /// </summary>
        internal static string BitText {
            get {
                return ResourceManager.GetString("BitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кабель.
        /// </summary>
        internal static string CableText {
            get {
                return ResourceManager.GetString("CableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap capture {
            get {
                object obj = ResourceManager.GetObject("capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap captureheader {
            get {
                object obj = ResourceManager.GetObject("captureheader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap capturempty {
            get {
                object obj = ResourceManager.GetObject("capturempty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация каналов:\t{2}\n.
        /// </summary>
        internal static string ChannelsGranularityText {
            get {
                return ResourceManager.GetString("ChannelsGranularityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмеченных: .
        /// </summary>
        internal static string CheckedText {
            get {
                return ResourceManager.GetString("CheckedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap color_mixer_search_256 {
            get {
                object obj = ResourceManager.GetObject("color_mixer_search_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnOrder.
        /// </summary>
        internal static string ColumnOrder {
            get {
                return ResourceManager.GetString("ColumnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запятая.
        /// </summary>
        internal static string CommaText {
            get {
                return ResourceManager.GetString("CommaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите выбор.
        /// </summary>
        internal static string ConfirmChoiceText {
            get {
                return ResourceManager.GetString("ConfirmChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить неотмеченные каналы? \n (Это может занять несколько минут).
        /// </summary>
        internal static string ConfirmDeleteChannelsText {
            get {
                return ResourceManager.GetString("ConfirmDeleteChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попытка соединения с сервером провалилась. Отчет об ошибке сформирован..
        /// </summary>
        internal static string ConnectionFailedText {
            get {
                return ResourceManager.GetString("ConnectionFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие видеозаписи....
        /// </summary>
        internal static string CurrentRecsText {
            get {
                return ResourceManager.GetString("CurrentRecsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущие напоминания.
        /// </summary>
        internal static string CurrentRemindsText {
            get {
                return ResourceManager.GetString("CurrentRemindsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string DateText {
            get {
                return ResourceManager.GetString("DateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДатаВремяПрограммаПередача.
        /// </summary>
        internal static string DateTimeProgramTelecastText {
            get {
                return ResourceManager.GetString("DateTimeProgramTelecastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить выделенные строки?.
        /// </summary>
        internal static string DeleteAllRowsText {
            get {
                return ResourceManager.GetString("DeleteAllRowsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: удаление неактуальных передач....
        /// </summary>
        internal static string DeletingOldCasts {
            get {
                return ResourceManager.GetString("DeletingOldCasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация размера кадра X:\t{6}\n.
        /// </summary>
        internal static string DetailsFrameSizeText {
            get {
                return ResourceManager.GetString("DetailsFrameSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация размера кадра Y:\t{7}\n.
        /// </summary>
        internal static string DetailsFrameSizeYText {
            get {
                return ResourceManager.GetString("DetailsFrameSizeYText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отобразить результат экспорта \n&apos;.
        /// </summary>
        internal static string DontShowExportResText1 {
            get {
                return ResourceManager.GetString("DontShowExportResText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.\n Возможно файл уже открыт..
        /// </summary>
        internal static string DontShowExportResText2 {
            get {
                return ResourceManager.GetString("DontShowExportResText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка.
        /// </summary>
        internal static string DotText {
            get {
                return ResourceManager.GetString("DotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить свежую ТВ-программу?.
        /// </summary>
        internal static string DownloadNewProgText {
            get {
                return ResourceManager.GetString("DownloadNewProgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка тв-программы из интернета....
        /// </summary>
        internal static string DownloadTVProgText {
            get {
                return ResourceManager.GetString("DownloadTVProgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка экспорта.
        /// </summary>
        internal static string ExportErrorText {
            get {
                return ResourceManager.GetString("ExportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт_тв-программы_{0}.xls.
        /// </summary>
        internal static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл экспорта: {0} открыт для просмотра. \n\n Необходимо закрыть файл..
        /// </summary>
        internal static string ExportFileOpenText {
            get {
                return ResourceManager.GetString("ExportFileOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт_тв-программы_результаты_поиска.xls.
        /// </summary>
        internal static string ExportResFileText {
            get {
                return ResourceManager.GetString("ExportResFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favorites25 {
            get {
                object obj = ResourceManager.GetObject("favorites25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Фильм).
        /// </summary>
        internal static string FilmText {
            get {
                return ResourceManager.GetString("FilmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форматы Windows Media не загружены, нечего выбирать!.
        /// </summary>
        internal static string FormatNotLoadedText {
            get {
                return ResourceManager.GetString("FormatNotLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Формат не поддерживается.\n.
        /// </summary>
        internal static string FormatNotSupportText {
            get {
                return ResourceManager.GetString("FormatNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передне-диагональный.
        /// </summary>
        internal static string ForwardDiagonalText {
            get {
                return ResourceManager.GetString("ForwardDiagonalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено .
        /// </summary>
        internal static string FoundText {
            get {
                return ResourceManager.GetString("FoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота видеопотока не поддерживается.\n.
        /// </summary>
        internal static string FrameRateNotSupportText {
            get {
                return ResourceManager.GetString("FrameRateNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер фрейма не поддерживается.\n.
        /// </summary>
        internal static string FrameSizeNotSupportText {
            get {
                return ResourceManager.GetString("FrameSizeNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота успешно сопоставлена..
        /// </summary>
        internal static string FreqComparedSuccessText {
            get {
                return ResourceManager.GetString("FreqComparedSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частота не была сопоставлена..
        /// </summary>
        internal static string FreqCompareNotSuccessText {
            get {
                return ResourceManager.GetString("FreqCompareNotSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fri {
            get {
                object obj = ResourceManager.GetObject("Fri", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fri_exp {
            get {
                object obj = ResourceManager.GetObject("Fri_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от .
        /// </summary>
        internal static string FromText {
            get {
                return ResourceManager.GetString("FromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenreEditor {
            get {
                object obj = ResourceManager.GetObject("GenreEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        internal static string GenreText {
            get {
                return ResourceManager.GetString("GenreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenAnons {
            get {
                object obj = ResourceManager.GetObject("GreenAnons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenAnonsFilt {
            get {
                object obj = ResourceManager.GetObject("GreenAnonsFilt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горизонтальный.
        /// </summary>
        internal static string HorizontalText {
            get {
                return ResourceManager.GetString("HorizontalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно записать перекрывающиеся\nпо времени передачи!.
        /// </summary>
        internal static string ImpossibleRecText {
            get {
                return ResourceManager.GetString("ImpossibleRecText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержимое файла телепрограммы в формате Интер-ТВ не распознано!.
        /// </summary>
        internal static string InvalidFormatInterTV {
            get {
                return ResourceManager.GetString("InvalidFormatInterTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кадра/с.
        /// </summary>
        internal static string KadraText {
            get {
                return ResourceManager.GetString("KadraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кадров/с.
        /// </summary>
        internal static string KadrovText {
            get {
                return ResourceManager.GetString("KadrovText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кбит/c.
        /// </summary>
        internal static string KbitText {
            get {
                return ResourceManager.GetString("KbitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключевые слова (фразы).
        /// </summary>
        internal static string KeywordsText {
            get {
                return ResourceManager.GetString("KeywordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кГц.
        /// </summary>
        internal static string KhzText {
            get {
                return ResourceManager.GetString("KhzText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка телепрограммы не удалась.
        /// </summary>
        internal static string LoadFail {
            get {
                return ResourceManager.GetString("LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телепрограмма успешно загружена!.
        /// </summary>
        internal static string LoadSuccess {
            get {
                return ResourceManager.GetString("LoadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логотип.
        /// </summary>
        internal static string LogoText {
            get {
                return ResourceManager.GetString("LogoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный размер кадра:\t{4} x {5}\n.
        /// </summary>
        internal static string MaxFrameSizeText {
            get {
                return ResourceManager.GetString("MaxFrameSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное число каналов:\t\t{1}\n.
        /// </summary>
        internal static string MaxNumberChannelsText {
            get {
                return ResourceManager.GetString("MaxNumberChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная частота видеопотока:\t{9:0.000} кадр./с\n.
        /// </summary>
        internal static string MaxRateVideoStreamText {
            get {
                return ResourceManager.GetString("MaxRateVideoStreamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальная частота:\t\t{7}\n.
        /// </summary>
        internal static string MaxSamplingRateText {
            get {
                return ResourceManager.GetString("MaxSamplingRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный размер кадра:\t{2} x {3}\n.
        /// </summary>
        internal static string MinFrameSizeText {
            get {
                return ResourceManager.GetString("MinFrameSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное число каналов:\t\t{0}\n.
        /// </summary>
        internal static string MinNumberChannelsText {
            get {
                return ResourceManager.GetString("MinNumberChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная частота видеопотока:\t{8:0.000} кадр./с\n.
        /// </summary>
        internal static string MinRateVideoStreamText {
            get {
                return ResourceManager.GetString("MinRateVideoStreamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная частота:\t\t{6}\n.
        /// </summary>
        internal static string MinSamplingRateText {
            get {
                return ResourceManager.GetString("MinSamplingRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mon {
            get {
                object obj = ResourceManager.GetObject("Mon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mon_exp {
            get {
                object obj = ResourceManager.GetObject("Mon_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моно.
        /// </summary>
        internal static string MonoText {
            get {
                return ResourceManager.GetString("MonoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затем.
        /// </summary>
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего не найдено.\nБудем менять критерии поиска?.
        /// </summary>
        internal static string NoFoundText {
            get {
                return ResourceManager.GetString("NoFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записей нет.
        /// </summary>
        internal static string NoRecordsText {
            get {
                return ResourceManager.GetString("NoRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминаний нет.
        /// </summary>
        internal static string NoRemindsText {
            get {
                return ResourceManager.GetString("NoRemindsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет запланированных записей.
        /// </summary>
        internal static string NoSettersRecordsText {
            get {
                return ResourceManager.GetString("NoSettersRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет установленных напоминаний.
        /// </summary>
        internal static string NoSettersRemindsText {
            get {
                return ResourceManager.GetString("NoSettersRemindsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Нет&gt;.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анонс.
        /// </summary>
        internal static string NoticeText {
            get {
                return ResourceManager.GetString("NoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас.
        /// </summary>
        internal static string NowText {
            get {
                return ResourceManager.GetString("NowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачность {0}%.
        /// </summary>
        internal static string OpacityProcText {
            get {
                return ResourceManager.GetString("OpacityProcText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запланированные записи.
        /// </summary>
        internal static string PlannedRecsText {
            get {
                return ResourceManager.GetString("PlannedRecsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, проверьте на корректность формат файла..
        /// </summary>
        internal static string PleaseCheckCorrectFormat {
            get {
                return ResourceManager.GetString("PleaseCheckCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, настройте нужные телеканалы....
        /// </summary>
        internal static string PleaseSetChannelsText {
            get {
                return ResourceManager.GetString("PleaseSetChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите видео и/или\nаудио устройство.
        /// </summary>
        internal static string PleaseSetVADeviceText {
            get {
                return ResourceManager.GetString("PleaseSetVADeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа.
        /// </summary>
        internal static string ProgramText {
            get {
                return ResourceManager.GetString("ProgramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  пт.
        /// </summary>
        internal static string PtText {
            get {
                return ResourceManager.GetString("PtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuestionCloud {
            get {
                object obj = ResourceManager.GetObject("QuestionCloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинги.
        /// </summary>
        internal static string RatingsText {
            get {
                return ResourceManager.GetString("RatingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        internal static string RatingText {
            get {
                return ResourceManager.GetString("RatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рекордер....
        /// </summary>
        internal static string RecorderText {
            get {
                return ResourceManager.GetString("RecorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записей: .
        /// </summary>
        internal static string RecordsText {
            get {
                return ResourceManager.GetString("RecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записать.
        /// </summary>
        internal static string RecText {
            get {
                return ResourceManager.GetString("RecText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно напоминания: выключено.
        /// </summary>
        internal static string ReminderWindowOff {
            get {
                return ResourceManager.GetString("ReminderWindowOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Окно напоминания: включено.
        /// </summary>
        internal static string ReminderWindowOn {
            get {
                return ResourceManager.GetString("ReminderWindowOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напоминаний: .
        /// </summary>
        internal static string RemindsText {
            get {
                return ResourceManager.GetString("RemindsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализации частоты:\t{8}\n.
        /// </summary>
        internal static string SamplingRateGranularityText {
            get {
                return ResourceManager.GetString("SamplingRateGranularityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sat {
            get {
                object obj = ResourceManager.GetObject("Sat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sat_exp {
            get {
                object obj = ResourceManager.GetObject("Sat_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satellite_dish {
            get {
                object obj = ResourceManager.GetObject("satellite_dish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satellite_dish2 {
            get {
                object obj = ResourceManager.GetObject("satellite_dish2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить все изменения?.
        /// </summary>
        internal static string SaveAllChangesText {
            get {
                return ResourceManager.GetString("SaveAllChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: поиск устаревших передач....
        /// </summary>
        internal static string SearchingOldCasts {
            get {
                return ResourceManager.GetString("SearchingOldCasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Установка стилей.
        /// </summary>
        internal static string SetStylesText {
            get {
                return ResourceManager.GetString("SetStylesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решётка.
        /// </summary>
        internal static string SharpText {
            get {
                return ResourceManager.GetString("SharpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывести передачи за неделю?.
        /// </summary>
        internal static string ShowAllProgramText {
            get {
                return ResourceManager.GetString("ShowAllProgramText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр канала....
        /// </summary>
        internal static string ShowChannelText {
            get {
                return ResourceManager.GetString("ShowChannelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детализация размера линии:\t{5}\n.
        /// </summary>
        internal static string SizeGranularityText {
            get {
                return ResourceManager.GetString("SizeGranularityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук: выключен.
        /// </summary>
        internal static string SoundOffText {
            get {
                return ResourceManager.GetString("SoundOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук: включен.
        /// </summary>
        internal static string SoundOnText {
            get {
                return ResourceManager.GetString("SoundOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробел.
        /// </summary>
        internal static string SpaceText {
            get {
                return ResourceManager.GetString("SpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: конвертация телепрограммы....
        /// </summary>
        internal static string StatusConvertingProgText {
            get {
                return ResourceManager.GetString("StatusConvertingProgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: построение деревьев списков....
        /// </summary>
        internal static string StatusCreatingTreesText {
            get {
                return ResourceManager.GetString("StatusCreatingTreesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: удаление лишних каналов....
        /// </summary>
        internal static string StatusDeleteChanText {
            get {
                return ResourceManager.GetString("StatusDeleteChanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: формирование набора данных....
        /// </summary>
        internal static string StatusFormingDataSetText {
            get {
                return ResourceManager.GetString("StatusFormingDataSetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: инициализация компонентов приложения....
        /// </summary>
        internal static string StatusInitText {
            get {
                return ResourceManager.GetString("StatusInitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: заключительные настройки....
        /// </summary>
        internal static string StatusLastsText {
            get {
                return ResourceManager.GetString("StatusLastsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: загрузка приложения....
        /// </summary>
        internal static string StatusLoadingAppText {
            get {
                return ResourceManager.GetString("StatusLoadingAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: централизация тв-программы....
        /// </summary>
        internal static string StatusMergingProg {
            get {
                return ResourceManager.GetString("StatusMergingProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: подготовка каналов и тв-программы....
        /// </summary>
        internal static string StatusPrepText {
            get {
                return ResourceManager.GetString("StatusPrepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: установка настроек приложения....
        /// </summary>
        internal static string StatusSetOptionsText {
            get {
                return ResourceManager.GetString("StatusSetOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус: установка параметров тв-тюнера....
        /// </summary>
        internal static string StatusSetTVTunerText {
            get {
                return ResourceManager.GetString("StatusSetTVTunerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стерео.
        /// </summary>
        internal static string StereoText {
            get {
                return ResourceManager.GetString("StereoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sun {
            get {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sun_exp {
            get {
                object obj = ResourceManager.GetObject("Sun_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передач: .
        /// </summary>
        internal static string Telecasts {
            get {
                return ResourceManager.GetString("Telecasts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передача.
        /// </summary>
        internal static string TelecastText {
            get {
                return ResourceManager.GetString("TelecastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ths {
            get {
                object obj = ResourceManager.GetObject("Ths", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ths_exp {
            get {
                object obj = ResourceManager.GetObject("Ths_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время с.
        /// </summary>
        internal static string TimeFromText {
            get {
                return ResourceManager.GetString("TimeFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время.
        /// </summary>
        internal static string TimeText {
            get {
                return ResourceManager.GetString("TimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомнить.
        /// </summary>
        internal static string ToRemindText {
            get {
                return ResourceManager.GetString("ToRemindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего каналов: .
        /// </summary>
        internal static string TotalChannelsText {
            get {
                return ResourceManager.GetString("TotalChannelsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие настройки:.
        /// </summary>
        internal static string TotalSettingsText {
            get {
                return ResourceManager.GetString("TotalSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  до .
        /// </summary>
        internal static string ToText {
            get {
                return ResourceManager.GetString("ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tue {
            get {
                object obj = ResourceManager.GetObject("Tue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tue_exp {
            get {
                object obj = ResourceManager.GetObject("Tue_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТВ-тюнер....
        /// </summary>
        internal static string TVTunerText {
            get {
                return ResourceManager.GetString("TVTunerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы передач.
        /// </summary>
        internal static string TypesOfTelecastsText {
            get {
                return ResourceManager.GetString("TypesOfTelecastsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отобразить возможности аудио.\n\n.
        /// </summary>
        internal static string UnableDisplayAudioCapText {
            get {
                return ResourceManager.GetString("UnableDisplayAudioCapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозомжно активизировать/деактивизировать\nпредпросмотр.
        /// </summary>
        internal static string UnablePreviewText {
            get {
                return ResourceManager.GetString("UnablePreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно установить цветовое пространство.\n.
        /// </summary>
        internal static string UnableSetColorSpaceText {
            get {
                return ResourceManager.GetString("UnableSetColorSpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отобразить свойства.
        /// </summary>
        internal static string UnableShowPropText {
            get {
                return ResourceManager.GetString("UnableShowPropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно отобразить возможности видео.\n\n.
        /// </summary>
        internal static string UnableShowVideoCapText {
            get {
                return ResourceManager.GetString("UnableShowVideoCapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра не поддерживается.\n.
        /// </summary>
        internal static string UnableSizeFrameText {
            get {
                return ResourceManager.GetString("UnableSizeFrameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя установить видеостандарт.\n.
        /// </summary>
        internal static string UnableVideoStandardText {
            get {
                return ResourceManager.GetString("UnableVideoStandardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вертикальный.
        /// </summary>
        internal static string VerticalText {
            get {
                return ResourceManager.GetString("VerticalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможности видеоустройства\n.
        /// </summary>
        internal static string VideoCapabilitiesText {
            get {
                return ResourceManager.GetString("VideoCapabilitiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеокодек не поддерживается..
        /// </summary>
        internal static string VideoCompressorNotSupportText {
            get {
                return ResourceManager.GetString("VideoCompressorNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеоустройство не поддерживается..
        /// </summary>
        internal static string VideoDeviceNotSupportText {
            get {
                return ResourceManager.GetString("VideoDeviceNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на входе:\t\t{0} x {1}\n.
        /// </summary>
        internal static string VideoInputSizeText {
            get {
                return ResourceManager.GetString("VideoInputSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеорежимы: {10}\n.
        /// </summary>
        internal static string VideoModesText {
            get {
                return ResourceManager.GetString("VideoModesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя установить этот источник.\nПожалуйста, обратитесь к отчету об ошибке.\n.
        /// </summary>
        internal static string VideoSourceNotSupportText {
            get {
                return ResourceManager.GetString("VideoSourceNotSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        internal static string VideoText {
            get {
                return ResourceManager.GetString("VideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео  (Переменный битрейт).
        /// </summary>
        internal static string VideoVariableBitrateText {
            get {
                return ResourceManager.GetString("VideoVariableBitrateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap volume_high {
            get {
                object obj = ResourceManager.GetObject("volume_high", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap volume_muted {
            get {
                object obj = ResourceManager.GetObject("volume_muted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wen {
            get {
                object obj = ResourceManager.GetObject("Wen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wen_exp {
            get {
                object obj = ResourceManager.GetObject("Wen_exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_dialog {
            get {
                object obj = ResourceManager.GetObject("window_dialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap window_dialog_none {
            get {
                object obj = ResourceManager.GetObject("window_dialog_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без рейтинга.
        /// </summary>
        internal static string WithoutRatingText {
            get {
                return ResourceManager.GetString("WithoutRatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без типа.
        /// </summary>
        internal static string WithoutTypeText {
            get {
                return ResourceManager.GetString("WithoutTypeText", resourceCulture);
            }
        }
    }
}
